v0.1.0
* Remove \r from mails (closes #11)
* Add headers at enqueue/sending (closes #7)
* Implement (un)hold feature (closes #1)
* Archive sent mails (closes #4)
* Fix config bug (closes #12)
* Fix various bugs

diff --git a/msmtp-yaqi b/msmtp-yaqi
--- a/msmtp-yaqi
+++ b/msmtp-yaqi
@@ -3,7 +3,7 @@
 #                                                                       #
 # msmtp-yaqi: Yet Another Queue Implementation for MSMTP                #
 # --------------------------------------------------------------------- #
-# Version 0.0.2 by Christian Schrötter <cs@fnx.li>                      #
+# Version 0.1.0 by Christian Schrötter <cs@fnx.li>                      #
 #                                                                       #
 # Inspired by msmtpq (Chris Gianniotis) and msmtpqueue (Martin Lambers) #
 #                                                                       #
@@ -109,6 +109,8 @@ function read_config
 	cfg[SYSLOG]=off
 	cfg[QUIET]=off
 	cfg[DEBUG]=off
+	cfg[HEADER]=off
+	cfg[ARCHIVE]=
 	cfg[DEFER]=300
 	cfg[UNDEV]=12
 	cfg[LIMIT]=0
@@ -141,11 +143,12 @@ function read_config
 	# Convert on/off values to integers
 	# TODO: case-insensitive, true, yes, 1, ...
 	[[ "${tmp[SYSLOG]}" == "on" ]] && cfg[SYSLOG]=1 || cfg[SYSLOG]=0
-	[[ "${tmp[QUIET]}" == "on" ]] && cfg[QUIET]=1 || cfg[QUIET]=0
-	[[ "${tmp[DEBUG]}" == "on" ]] && cfg[DEBUG]=1 || cfg[DEBUG]=0
+	[[ "${tmp[QUIET]}"  == "on" ]] && cfg[QUIET]=1  || cfg[QUIET]=0
+	[[ "${tmp[DEBUG]}"  == "on" ]] && cfg[DEBUG]=1  || cfg[DEBUG]=0
+	[[ "${tmp[HEADER]}" == "on" ]] && cfg[HEADER]=1 || cfg[HEADER]=0
 
 	[[ -z "${tmp[QUEUE]}" ]] \
-	&& log -e 78 "Empty QUEUE path in $(basename "$1")"
+	&& log -e 78 "Empty QUEUE path in $(basename -- "$1")"
 
 	# Queue directory: Absolute path or relative to $HOME
 	[[ -n "${tmp[QUEUE]}" && "${tmp[QUEUE]:0:1}" != "/" ]] \
@@ -160,6 +163,15 @@ function read_config
 	&& cfg[LOGFILE]="$HOME/${tmp[LOGFILE]}" \
 	|| cfg[LOGFILE]="${tmp[LOGFILE]}"
 
+	# Archive directory: Absolute path or relative to $HOME
+	[[ -n "${tmp[ARCHIVE]}" && "${tmp[ARCHIVE]:0:1}" != "/" ]] \
+	&& cfg[ARCHIVE]="$HOME/${tmp[ARCHIVE]}" \
+	|| cfg[ARCHIVE]="${tmp[ARCHIVE]}"
+
+	[[ -n "${cfg[ARCHIVE]}" ]] \
+	&& [[ ! -d "${cfg[ARCHIVE]}" || ! -w "${cfg[ARCHIVE]}" ]] \
+	&& log -e 78 "Invalid ARCHIVE path: ${cfg[ARCHIVE]}"
+
 	# Convert elements to integers
 	cfg[DEFER]=$(printf '%d' "${tmp[DEFER]}")
 	cfg[UNDEV]=$(printf '%d' "${tmp[UNDEV]}")
@@ -170,6 +182,10 @@ function read_config
 	[[ "${cfg[UNDEV]}" -lt 0 ]] && cfg[UNDEV]=0
 	[[ "${cfg[LIMIT]}" -lt 0 ]] && cfg[LIMIT]=0
 
+	# Copy remaining items
+	cfg[MSMTP]="${tmp[MSMTP]}"
+	cfg[LOGFILE_TIME_FORMAT]="${tmp[LOGFILE_TIME_FORMAT]}"
+
 	log -d "Read configuration from file $1"
 	log -d "--------------------------------------------------"
 	log -d "  \$cfg[MSMTP]=${cfg[MSMTP]}"
@@ -179,10 +195,24 @@ function read_config
 	log -d "  \$cfg[SYSLOG]=${cfg[SYSLOG]}"
 	log -d "  \$cfg[QUIET]=${cfg[QUIET]}"
 	log -d "  \$cfg[DEBUG]=${cfg[DEBUG]}"
+	log -d "  \$cfg[HEADER]=${cfg[HEADER]}"
+	log -d "  \$cfg[ARCHIVE]=${cfg[ARCHIVE]}"
 	log -d "  \$cfg[DEFER]=${cfg[DEFER]}"
 	log -d "  \$cfg[UNDEV]=${cfg[UNDEV]}"
 	log -d "  \$cfg[LIMIT]=${cfg[LIMIT]}"
 	log -d "--------------------------------------------------"
+}
+
+# hold_queue [-u]
+function hold_queue
+{
+	for file in "${cfg[QUEUE]}"/*-*-*,*
+	do
+		[[ ! -f "$file" ]] && continue
+
+		# shellcheck disable=SC2086
+		hold_mails ${1:-} "$(basename -- "$file" | cut -d , -f 1)"
+	done
 }
 
 function purge_queue
@@ -190,7 +220,9 @@ function purge_queue
 	for file in "${cfg[QUEUE]}"/*-*-*,*
 	do
 		[[ ! -f "$file" ]] && continue
-		purge_mails "$(basename "$file" | cut -d , -f 1)"
+		holding "$file" && continue
+
+		purge_mails "$(basename -- "$file" | cut -d , -f 1)"
 	done
 }
 
@@ -210,6 +242,7 @@ function run_queue
 	do
 		[[ ! -f "$file" ]] && continue
 		get_details "$file" -; ((c++))
+		[[ "$queue_hold" -eq 1 ]] && continue
 
 		if [[ "$flush" -eq 0 && "${cfg[DEFER]}" -gt 0 && "$queue_tries" -gt 0 && "$((current-queue_mtime))" -lt "$((2**(queue_tries-1)*cfg[DEFER]))" ]]
 		then
@@ -220,7 +253,13 @@ function run_queue
 		send_mails "$queue_id" \
 		|| state=$?
 
-		[[ "${cfg[UNDEV]}" -gt 0 && "$((queue_tries+1))" -ge "${cfg[UNDEV]}" ]] && purge_mails "$queue_id"
+		[[ \
+			"$state" -ne 0 && \
+			"${cfg[UNDEV]}" -gt 0 && \
+			"$((queue_tries+1))" -ge "${cfg[UNDEV]}"\
+		 ]] \
+		 && purge_mails "$queue_id"
+
 		if [[ "$flush" -eq 0 && "${cfg[DEFER]}" -gt 0 && "${cfg[LIMIT]}" -gt 0 && "$c" -ge "${cfg[LIMIT]}" ]]
 		then
 			log -d "Per-run limit reached, stopping now..."
@@ -234,12 +273,13 @@ function run_queue
 # send_mails <ID> ...
 send_mails()
 {
-	local q f file
+	local q h='' f file
 	local -i state=0
+	local -i c
 
 	for q in "$@"
 	do
-		q=$(basename "$q")
+		q=$(basename -- "$q")
 		file=""
 
 		for f in "${cfg[QUEUE]}/$q",*
@@ -260,6 +300,20 @@ send_mails()
 
 		get_header "$file"
 		get_content "$file"
+		get_details "$file"
+
+		c=$((queue_tries+1))
+		[[ "$queue_hold" -eq 1 ]] \
+		&& h="HOLD; "
+
+		if [[ "${cfg[HEADER]}" -eq 1 ]]
+		then
+			# Prepend current timestamp as new header.
+			queue_content="X-MSMTP-Sent: $(date +'%a, %d %b %Y %T %z')"$'\n'"$queue_content"
+
+			# Prepend try-counter as new header.
+			[[ "$queue_hold" -eq 0 ]] && queue_content="X-MSMTP-Try: $c"$'\n'"$queue_content"
+		fi
 
 		# shellcheck disable=SC2086
 		"${cfg[MSMTP]}" $queue_header \
@@ -268,14 +322,22 @@ send_mails()
 
 		if [[ "$state" -ne 0 ]]
 		then
-			# Increment try-counter in filename by renaming the queue file.
-			counter=$(cut -d , -f 2 <<< "$(basename "$file")"); mv "$file" "${cfg[QUEUE]}/$q,$((counter+1))"
-			log "Failed to send queued message: ID $q (try=$((counter+1))$([[ "${cfg[UNDEV]}" -gt 0 ]] && echo "/${cfg[UNDEV]}"); status=$state)"
+			log "Failed to send queued message: ID $q (${h}try=${queue_tries}$([[ "${cfg[UNDEV]}" -gt 0 ]] && echo "/${cfg[UNDEV]}"); status=${state})"
+
+			if [[ "$queue_hold" -eq 0 ]]
+			then
+				mv "$file" "${cfg[QUEUE]}/$q,$c" \
+				|| log -e 74 "Could not increment try-counter: ID $q ($queue_rtries -> $c)" # EX_IOERR
+			fi
+
 			continue
 		fi
 
-		log "Queued message sent: ID $q"
 		purge_mails "$q"
+		log "Queued message sent: ID $q"
+
+		[[ -n "${cfg[ARCHIVE]}" && ! -e "${cfg[ARCHIVE]}/$q.eml" ]] \
+		&& echo "$queue_content" > "${cfg[ARCHIVE]}/$q.eml"
 	done
 
 	return "$state"
@@ -289,7 +351,7 @@ purge_mails()
 
 	for q in "$@"
 	do
-		q=$(basename "$q")
+		q=$(basename -- "$q")
 		file=""
 
 		for f in "${cfg[QUEUE]}/$q",*
@@ -333,7 +395,10 @@ display_queue()
 		echo
 		echo -n " Message #$i in queue"
 
-		if [[ "$((queue_tries))" -gt 0 || "${cfg[UNDEV]}" -eq 1 ]]
+		if [[ "$queue_hold" -eq 1 ]]
+		then
+			echo " [HOLD]"
+		elif [[ "$((queue_tries))" -gt 0 || "${cfg[UNDEV]}" -eq 1 ]]
 		then
 			echo -n " (try $((queue_tries+1))"
 			[[ "${cfg[UNDEV]}" -gt 0 ]] \
@@ -370,19 +435,26 @@ function get_details
 {
 	local b
 	declare -g queue_id
+	declare -g -i queue_rtries=0
 	declare -g -i queue_tries=0
 	declare -g -i queue_mtime=0
+	declare -g -i queue_hold=-1
 
 	unset queue_id
 	unset queue_tries
 	unset queue_mtime
 
-	b=$(basename "$1")
+	b=$(basename -- "$1")
 	queue_id=$(cut -d , -f 1 <<< "$b")
-	queue_tries=$(cut -d , -f 2 <<< "$b")
+	queue_rtries=$(cut -d , -f 2 <<< "$b")
+	queue_tries=${queue_rtries#-}
 
-	[[ -n "${2:-}" ]] && \
-	queue_mtime=$(stat -c %Y "$1")
+	holding "$b" \
+	&& queue_hold=1 \
+	|| queue_hold=0
+
+	[[ -n "${2:-}" ]] \
+	&& queue_mtime=$(stat -c %Y "$1")
 }
 
 # Get msmtp argument list from queue file.
@@ -423,9 +495,18 @@ function enqueue_mail
 	[[ -f "$queue_file" ]] || ls "$queue_file",* &>/dev/null \
 	&& log -e 1 "Queue file already exists: ID $queue_id"
 
-	# Write escaped arguments and mail content to temporary queue file.
+	# Write escaped arguments to temporary queue file.
 	cat <<< "$(printf '%q\n' "$@" | tr '\n' ' ')" > "$queue_file" || log -e "$?" "Queue header write failed: ID $queue_id"
-	cat >> "$queue_file" || log -e "$?" "Queue content write failed: ID $queue_id"
+
+	if [[ "${cfg[HEADER]}" -eq 1 ]]
+	then
+		# Prepend current timestamp as new header.
+		echo "X-MSMTP-Queue: $(date +'%a, %d %b %Y %T %z')" >> "$queue_file" \
+		|| log -e "$?" "Queue header injection failed: ID $queue_id"
+	fi
+
+	# Write mail content to temporary queue file.
+	cat | tr -d '\r' >> "$queue_file" || log -e "$?" "Queue content write failed: ID $queue_id"
 
 	# Move queue file to final destination with retry-counter value "0" appended.
 	mv "$queue_file" "$queue_file,0" || log -e "$?" "Queue file release failed: ID $queue_id"
@@ -472,6 +553,60 @@ function lock_queue
 	fi
 }
 
+# Message hold?
+function holding
+{
+	grep -qF ',-' <<< "$(basename -- "$1")"
+	return $?
+}
+
+# hold_mails [-u] <ID> ...
+hold_mails()
+{
+	local q n f file
+	local -i state=0
+	local -i action=1
+
+	if [[ "${1:-}" == '-u' ]]
+	then
+		action=0
+		shift
+	fi
+
+	for q in "$@"
+	do
+		q=$(basename -- "$q")
+		file=""
+
+		for f in "${cfg[QUEUE]}/$q",*
+		do
+			if [[ -f "$f" ]]
+			then
+				file=$f
+				break;
+			fi
+		done
+
+		if [[ -z "$file" ]]
+		then
+			stderr "Queue ID $q not found."
+			state=66 # EX_NOINPUT
+			continue
+		fi
+
+		get_details "$file"
+		[[ "$queue_hold" -eq "$action" ]] && continue
+		n=$queue_tries; [[ "$action" -eq 1 ]] && n=$((0-n))
+
+		mv "$file" "${cfg[QUEUE]}/$q,$n" \
+		|| log -e 74 "Could not (un)hold message: ID $q" # EX_IOERR
+		[[ "$action" -eq 1 ]] && log "Message from queue hold: ID $q"
+		[[ "$action" -ne 1 ]] && log "Message released into queue: ID $q"
+	done
+
+	return "$state"
+}
+
 # Trap callback.
 function cleanup
 {
@@ -489,7 +624,7 @@ function cleanup
 export LANG=C
 declare -i ec=0
 set -u -o pipefail
-BASECMD=$(basename "$0")
+BASECMD=$(basename -- "$0")
 unset queue_file
 unset locked
 umask 0077
@@ -515,7 +650,13 @@ then
 	shift
 
 	case "${OP:1}" in
-		f|r|R|p|a|d|'')
+		f|r|a|n|N|d|'')
+			[[ -n "${1:-}" ]] && error "Too many arguments for option '$OP'"
+			;;
+
+		R|H|U|p)
+			[[ -z "${1:-}" ]] && error "Too few arguments for option '$OP'"
+			[[ "$OP" == "-H" && "$1" == "-u" ]] && error "Invalid queue ID"
 			;;
 
 		e)
@@ -550,6 +691,14 @@ then
 			echo '## Enable all debug messages? (Only for development!)'
 			echo '## Will be logged to file and syslog too if enabled.'
 			echo '#DEBUG=off'
+			echo
+			echo '## Add additional headers at enqueue and while sending?'
+			echo '## Contains enqueue timestamp and internal retry counter.'
+			echo '#HEADER=off'
+			echo
+			echo '## Sent mails archive directory.'
+			echo '## Relative to $''HOME path!'
+			echo '#ARCHIVE='
 			echo
 			echo '## Wait time after failed delivery tries.'
 			echo '## Will be doubled after each failed retry!'
@@ -591,8 +740,12 @@ then
 			stderr "  -f             flush mail queue (force delivery)"
 			stderr "  -r             run mail queue (honor wait times)"
 			stderr "  -R [<ID> ...]  send selected mail(s) from queue"
+			stderr "  -H [<ID> ...]  hold selected mail(s) in queue (do not deliver)"
+			stderr "  -U [<ID> ...]  release selected mail(s) from hold (deliver again)"
 			stderr "  -p [<ID> ...]  purge selected mail(s) from queue"
 			stderr "  -a             purge all mails from queue"
+			stderr "  -n             hold all mails at queue"
+			stderr "  -N             unhold all mails at queue"
 			stderr "  -d             display mails in queue"
 			stderr "  -e             show example config"
 			stderr "  -h             show help message"
@@ -611,12 +764,16 @@ then
 	case "${OP:1}"
 	in
 
-		f) run_queue -f    ; ec=$? ;; # flush queue
-		r) run_queue       ; ec=$? ;; # run the queue (cron)
-		R) send_mails "$@" ; ec=$? ;; # send individual mail(s)
-		p) purge_mails "$@"; ec=$? ;; # purge individual mail(s)
-		a) purge_queue     ; ec=$? ;; # purge all mails in queue
-		*) display_queue   ; ec=$? ;; # display queue (default)
+		f) run_queue   -f      ; ec=$? ;; # flush queue
+		r) run_queue           ; ec=$? ;; # run the queue (cron)
+		R) send_mails     "$@" ; ec=$? ;; # send individual mail(s)
+		H) hold_mails     "$@" ; ec=$? ;; # hold individual mail(s)
+		U) hold_mails  -u "$@" ; ec=$? ;; # unhold individual mail(s)
+		p) purge_mails    "$@" ; ec=$? ;; # purge individual mail(s)
+		a) purge_queue         ; ec=$? ;; # purge all mails in queue
+		n) hold_queue          ; ec=$? ;; # hold all mails at queue
+		N) hold_queue  -u      ; ec=$? ;; # unhold all mails at queue
+		*) display_queue       ; ec=$? ;; # display queue (default)
 
 	esac
 	lock_queue -u
