...

diff --git a/src/msmtpq b/src/msmtpq
--- a/src/msmtpq
+++ b/src/msmtpq
@@ -14,9 +14,24 @@
 
 # Alias for echo command.
 # Redirect it to STDERR.
-stderr()
+function stderr
 {
 	echo "$@" 1>&2
+}
+
+# Multi-line version of stderr().
+# Adds the program basename as prefix.
+# And exits after outputting all lines.
+function error
+{
+	local var
+
+	for var in "$@"
+	do
+		stderr "$BASECMD: $var"
+	done
+
+	exit 1
 }
 
 # Debug:   log -d        [<MSG> ...]
@@ -163,23 +178,6 @@ function read_config
 	log -d "--------------------------------------------------"
 }
 
-err()
-{
-	stderr -n "$BASECMD: "
-
-	if [[ "$#" -gt 0 ]]
-	then
-		for var in "$@"
-		do
-			stderr "$var"
-		done
-	else
-		stderr
-	fi
-
-	exit 1
-}
-
 # Trap callback.
 function cleanup
 {
@@ -210,10 +208,10 @@ lock_queue()
 		done
 
 		[ -z "$locked" ] && \
-			err '' "cannot use queue ${cfg[QUEUE]} : waited $MAX seconds for"\
-				   "  lockdir [ $LOK ] to vanish ; giving up"\
-				   'if you are certain that no other instance of this script'\
-				   "  is running, then 'rmdir' the lock dir manually" '' # lock file still there, give up
+			error '' "cannot use queue ${cfg[QUEUE]} : waited $MAX seconds for"\
+				     "  lockdir [ $LOK ] to vanish ; giving up"\
+				     'if you are certain that no other instance of this script'\
+				     "  is running, then 'rmdir' the lock dir manually" '' # lock file still there, give up
 
 	elif [[ "$1" == '-u' ]]
 	then
@@ -453,7 +451,7 @@ display_queue()
 	done
 
 	[[ "$i" -eq 0 ]] \
-	&& err 'No mail in queue'
+	&& error 'No mail in queue'
 
 	echo
 }
@@ -510,7 +508,7 @@ umask 0077
 
 # Load user configuration.
 # Or fallback to defaults.
-read_config ~/.msmtpq.cfg
+read_config ~/.msmtpq.conf
 
 # Remove queue locking
 # and delete $queue_file
@@ -541,15 +539,65 @@ then
 		a)    purge_queue        ;; # purge all mails in queue
 		d|'') display_queue      ;; # display queue (default)
 
+		e)
+			echo '############################################################'
+			echo '# msmtp-yaqi example configuration file: ~/.msmtpq.conf    #'
+			echo '#  Looks like Bash but it is a simple plaintext format!    #'
+			echo '############################################################'
+			echo
+			echo '## Path to msmtp binary'
+			echo '#MSMTP=msmtp'
+			echo
+			echo '## Path to queue directory. Relative to $HOME path!'
+			echo '##   mkdir -v ~/.msmtpq && chmod -c 0700 ~/.msmtpq'
+			echo '#QUEUE=.msmtpq'
+			echo
+			echo '## Path to logfile.'
+			echo '## Relative to $HOME!'
+			echo '## Disabled by default.'
+			echo '#LOGFILE='
+			echo
+			echo '## Prefixed timestamp format for logfile.'
+			echo '#LOGFILE_TIME_FORMAT=%Y-%m-%d %H:%M:%S'
+			echo
+			echo '## Log to syslog?'
+			echo '## Facility mail.*'
+			echo '#SYSLOG=off'
+			echo
+			echo '## Output log messages to STDERR too?'
+			echo '## Facility: mail.{debug,info,warn,err}'
+			echo '#QUIET=off'
+			echo
+			echo '## Enable all debug messages? (Only for development!)'
+			echo '## Will be logged to file and syslog too if enabled.'
+			echo '#DEBUG=off'
+			echo
+			echo '## Wait time after failed delivery tries.'
+			echo '## Will be doubled after each failed retry!'
+			echo '## State estimated per message, not globally.'
+			echo '## Always and only calculated by enqueue time.'
+			echo '## Time in seconds. Use "0" to disable it.'
+			echo '#DEFER=300'
+			echo
+			echo '## Count message as undeliverable after <n> retries.'
+			echo '## The message will be deleted from queue and is lost.'
+			echo '## Use "0" to disable this feature. (Not recommended!)'
+			echo '## Estimate your best value: $((2 ** (<n> - 1) * DEFER))'
+			echo '#UNDEV=12'
+			echo
+			echo '## Maximum elements per run with -r.'
+			echo '## Works only, when DEFER is enabled.'
+			echo '## This feature is disabled by default.'
+			echo '#LIMIT=0'
+			;;
+
 		h)
-			stderr "=========================================="
-			stderr "Yet Another Queue Implementation for MSMTP"
-			stderr "=========================================="
-			stderr
 			stderr "Usage: msmtpq [sendmail options]"
 			stderr
-			stderr "       msmtpq --q-mgmt <OP> [<ARGS> ...]"
-			stderr "        or msmtp-queue <OP> [<ARGS> ...]"
+			stderr "    or msmtpq --q-mgmt <OP> [<ARGS> ...]"
+			stderr "    or msmtp-queue <OP> [<ARGS> ...]"
+			stderr
+			stderr "Yet Another Queue Implementation for MSMTP"
 			stderr
 			stderr "Sendmail mode:"
 			stderr
@@ -565,64 +613,14 @@ then
 			stderr "  -R [<ID> ...]  send selected mail(s) from queue"
 			stderr "  -p [<ID> ...]  purge selected mail(s) from queue"
 			stderr "  -a             purge all mails from queue"
-			stderr "  -d             display queue list"
+			stderr "  -d             display mails in queue"
+			stderr "  -e             show example config"
 			stderr "  -h             show help message"
-			stderr
-			stderr "#########################################"
-			stderr "## Configuration file: ~/.msmtpq.conf   #"
-			stderr "## Looks like Bash but it's plaintext!  #"
-			stderr "#########################################"
-			stderr "#"
-			stderr "## Path to msmtp binary"
-			stderr "#MSMTP=msmtp"
-			stderr "#"
-			stderr "## Path to queue directory. Relative to \$HOME path!"
-			stderr "##   mkdir -v ~/.msmtpq && chmod -c 0700 ~/.msmtpq"
-			stderr "#QUEUE=.msmtpq"
-			stderr "#"
-			stderr "## Path to logfile."
-			stderr "## Relative to \$HOME!"
-			stderr "## Disabled by default."
-			stderr "#LOGFILE="
-			stderr "#"
-			stderr "## Prefixed timestamp format for logfile."
-			stderr "#LOGFILE_TIME_FORMAT=%Y-%m-%d %H:%M:%S"
-			stderr "#"
-			stderr "## Log to syslog?"
-			stderr "## Facility mail.*"
-			stderr "#SYSLOG=off"
-			stderr "#"
-			stderr "## Output log messages to STDERR too?"
-			stderr "## Facility: mail.{debug,info,warn,err}"
-			stderr "#QUIET=off"
-			stderr "#"
-			stderr "## Enable all debug messages? (Only for development.)"
-			stderr "## Will be logged to file and syslog too if enabled!"
-			stderr "#DEBUG=off"
-			stderr "#"
-			stderr "## Wait time after failed delivery tries."
-			stderr "## Will be doubled after each failed retry!"
-			stderr "## State estimated per message, not globally."
-			stderr "## Always and only calculated by enqueue time."
-			stderr "## Time in seconds. Use \"0\" to disable it."
-			stderr "#DEFER=300"
-			stderr "#"
-			stderr "## Count message as undeliverable after <n> retries."
-			stderr "## The message will be deleted from queue and is lost."
-			stderr "## Use \"0\" to disable this feature. (Not recommended!)"
-			stderr "## Estimate your best value: \$((2 ** (<n> - 1) * DEFER))"
-			stderr "#UNDEV=12"
-			stderr "#"
-			stderr "## Maximum elements per run with -r."
-			stderr "## Works only, when DEFER is enabled."
-			stderr "## This feature is disabled by default."
-			stderr "#LIMIT=0"
-			exit 1
 			;;
 
 		*)
-			err "unrecognized option '$OP'" \
-			    "Try '-h' for more information."
+			error "unrecognized option '$OP'" \
+			      "Try '-h' for more information."
 			;;
 	esac
 
